auth:
  region: us-east-1
  service: s3
  # WARNING: Example keys only - do not use in production
  keys:
    - access_key: FE373CEF5632FDED3081
      secret_key: 9218d0ddfdb1779169f4b6b3b36df321099e98e9

access:
  public_read: false
  public_write: false

cors:
  enabled: true
  allowed_origins:
    - "*"
  allowed_methods:
    - GET
    - PUT
    - DELETE
    - OPTIONS
  allowed_headers:
    - Content-Type
    - Authorization
    - X-Amz-Date
    - X-Amz-Content-Sha256
  exposed_headers:
    - ETag
    - Content-Length
  max_age: 300
